### ISSUE TITLE
[feat] Allow prototypes to inherit

### ISSUE THREAD

**Issue by fritzduchardt** [mykso/myks#109]
We provide generic helm and ytt configuration in environment group folders, e.g. "envs/kubermatic-clusters" under "_apps/app-name". However, if a user wants to install the same app multiple times on the same environment, e.g. a web-service with slight modification for multiple different customers, the current concept does not permit this.

This could be made to work, by using the folder naming of "prototypes" instead: "_apps/base-app-name" or "_apps/base-app-group/base-app-name".

**Comment by Zebradil** [comment]
I'm not entirely sure I understand the problem.

Do you want to create new reusable flavours of a prototype by placing a special configuration somewhere under `envs` directory?

Or do you mean there is a naming problem?

**Comment by Zebradil** [comment]
I've checked the corresponding PR. I think I better understand the idea now.

However, the proposed approach feels confusing, because, depending on the file tree level, `_apps/foo` means different things: is `foo` a prototype or an application?

If you really don't want to create a separate prototype for a group of applications you want to customize in the same way, we can think of a `_proto` directory next to the `_apps` directory. 

Or we can think about changing the structure of the prototypes themselves to make them also be assembled from a tree-like structure. Though, this doesn't look like a better idea at the moment.
